"use client";

import { useEffect, useMemo, useState } from "react";

type Account={id:string;alias:string;holder_name:string;holder_cpf:string;program:string;member_number?:string;azul_category?:string;archived:boolean;history_incomplete:boolean};
type Card={account_id:string;program:string;alias:string;holder_name:string;holder_cpf:string;used:number;limit:number;remaining:number;percent:number;next_release:string|null;rule_pending:boolean;history_incomplete:boolean;cpf_rows:Array<{cpf:string;first:string;last:string;emissions:number;release:string|null}>;azul_beneficiaries:Array<{id:string;name:string;cpf:string;effective_on:string;status:string;release_on:string|null;inclusion_type:string;is_child:boolean;relationship_confirmed:boolean;exemption_confirmed:boolean}>};
type Emission={id:string;account_id:string;issued_on:string;locator:string|null;operating_airline:string|null;flight_on:string|null;status:string;alias:string;program:string};
type Passenger={id:string;emission_id:string;account_id:string;name:string;cpf:string;issued_on:string;status:string;released_at:string|null};
type Data={accounts:Account[];emissions:Emission[];passengers:Passenger[];cards:Card[];rules:Array<{program:string;account_id:string|null;limit_count:number;waiting_days:number;source:string;valid_from:string;checked_on:string;active:boolean;confirmed:boolean}>;canManage:boolean};
const today=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"America/Sao_Paulo"}).format(new Date());
const headers={"Content-Type":"application/json","X-RM-CSRF":"1"};
const moneyDate=(v:string|null|undefined)=>v?new Date(`${v.slice(0,10)}T12:00:00`).toLocaleDateString("pt-BR"):"—";

export default function CpfControl(){
  const [data,setData]=useState<Data|null>(null),[error,setError]=useState(""),[notice,setNotice]=useState(""),[tab,setTab]=useState("visao"),[busy,setBusy]=useState(false);
  const emptyAccount={id:"",alias:"",holderName:"",holderCpf:"",program:"LATAM Pass",memberNumber:"",azulCategory:"Básico",historyIncomplete:false};
  const [account,setAccount]=useState(emptyAccount);
  const [issue,setIssue]=useState({accountId:"",issuedOn:today(),locator:"",airline:"",flightOn:"",status:"emitido",notes:"",justification:"",passengers:[{name:"",cpf:""}]});
  const [beneficiary,setBeneficiary]=useState({accountId:"",name:"",cpf:"",effectiveOn:today(),inclusionType:"inicial",isChild:false,relationshipConfirmed:false,exemptionConfirmed:false});
  const [rule,setRule]=useState({program:"LATAM Pass",accountId:"",limit:"24",waitingDays:"30",source:"",validFrom:today(),checkedOn:today(),confirmed:false});
  const [filters,setFilters]=useState({program:"",account:"",search:"",status:"",from:"",to:""});
  const refresh=async()=>{const r=await fetch("/api/cpf-control",{cache:"no-store"});const j=await r.json();if(!r.ok)throw Error(j.error||"Falha ao carregar.");setData(j);};
  useEffect(()=>{void refresh().catch(e=>setError(e.message));},[]);
  const send=async(payload:Record<string,unknown>)=>{setBusy(true);setError("");setNotice("");try{const r=await fetch("/api/cpf-control",{method:"POST",headers,body:JSON.stringify(payload)});const j=await r.json();if(!r.ok)throw Error(j.error||"Falha ao salvar.");await refresh();return j;}catch(e){setError(e instanceof Error?e.message:"Falha ao salvar.");return null;}finally{setBusy(false);}};
  const reveal=async(kind:string,id:string)=>{const reason=window.prompt("Motivo para consultar o CPF completo (registrado em auditoria):");if(!reason)return;const r=await send({action:"reveal",kind,id,reason});if(r?.cpf)window.alert(`CPF: ${r.cpf}`);};
  const accounts=data?.accounts||[],cards=data?.cards||[];
  const visibleEmissions=useMemo(()=>{if(!data)return[];return data.emissions.filter(e=>(!filters.program||e.program===filters.program)&&(!filters.account||e.account_id===filters.account)&&(!filters.status||e.status===filters.status)&&(!filters.from||e.issued_on>=filters.from)&&(!filters.to||e.issued_on<=filters.to)&&(!filters.search||data.passengers.some(p=>p.emission_id===e.id&&`${p.name} ${p.cpf}`.toLocaleLowerCase().includes(filters.search.toLocaleLowerCase()))));},[data,filters]);
  const updatePassenger=(i:number,key:"name"|"cpf",value:string)=>setIssue(v=>({...v,passengers:v.passengers.map((p,n)=>n===i?{...p,[key]:value}:p)}));
  const azulAccounts=accounts.filter(a=>a.program==="Azul Fidelidade"&&!a.archived);
  return <div className="cpf-control">
    <header className="cpf-head"><div><h1>Controle de CPFs</h1><p>Uso de passageiros por conta que forneceu as milhas.</p></div><button className="dark-mini" onClick={()=>void refresh()}>Atualizar</button></header>
    {error?<p className="cpf-alert error" role="alert">{error}</p>:null}{notice?<p className="cpf-alert">{notice}</p>:null}
    <div className="cpf-tabs">{[["visao","Contas"],["emissoes","Emissões"],["azul","Beneficiários Azul"],...(data?.canManage?[["regras","Regras"]]:[])] .map(([key,label])=><button key={key} className={tab===key?"active":""} onClick={()=>setTab(key)}>{label}</button>)}</div>
    {tab==="visao"?<>
      {data?.canManage?<form className="cpf-form" onSubmit={async e=>{e.preventDefault();const r=await send({action:"account",...account});if(r){setAccount(emptyAccount);setNotice(account.id?"Conta atualizada.":"Conta cadastrada.");}}}>
        <h2>{account.id?"Editar conta de milhas":"Nova conta de milhas"}</h2><div className="cpf-fields"><label>Apelido<input className="input" required value={account.alias} onChange={e=>setAccount({...account,alias:e.target.value})}/></label><label>Titular<input className="input" required value={account.holderName} onChange={e=>setAccount({...account,holderName:e.target.value})}/></label><label>CPF do titular<input className="input" required={!account.id} placeholder={account.id?"Em branco mantém o CPF atual":"11 dígitos"} inputMode="numeric" value={account.holderCpf} onChange={e=>setAccount({...account,holderCpf:e.target.value})}/></label><label>Programa<select className="input" value={account.program} onChange={e=>setAccount({...account,program:e.target.value})}><option>LATAM Pass</option><option>Smiles</option><option>Azul Fidelidade</option></select></label><label>Associado (opcional)<input className="input" value={account.memberNumber} onChange={e=>setAccount({...account,memberNumber:e.target.value})}/></label>{account.program==="Azul Fidelidade"?<label>Categoria Azul<select className="input" value={account.azulCategory} onChange={e=>setAccount({...account,azulCategory:e.target.value})}>{["Básico","Topázio","Safira","Diamante","Diamante Unique"].map(x=><option key={x}>{x}</option>)}</select></label>:null}<label className="cpf-check"><input type="checkbox" checked={account.historyIncomplete} onChange={e=>setAccount({...account,historyIncomplete:e.target.checked})}/> Histórico da conta incompleto</label><button className="primary-button" disabled={busy}>{account.id?"Salvar edição":"Cadastrar conta"}</button>{account.id?<button type="button" className="dark-mini" onClick={()=>setAccount(emptyAccount)}>Cancelar edição</button>:null}</div><small>Não armazene senhas dos programas. O CPF é validado e mantido como texto.</small>
      </form>:null}
      {!cards.length?<p className="cpf-empty">Nenhuma conta cadastrada.</p>:<div className="cpf-cards">{cards.map(c=><article className="cpf-card" key={c.account_id}><div className="cpf-card-title"><div><span>{c.program}</span><h2>{c.alias}</h2><small>{c.holder_name} · CPF {c.holder_cpf} {data?.canManage?<button className="cpf-text-button" onClick={()=>void reveal("holder",c.account_id)}>ver completo</button>:null}</small></div><span className={`cpf-badge ${c.rule_pending?"pending":c.limit&&c.percent>=1?"full":c.percent>=.8?"attention":"normal"}`}>{c.rule_pending?"Regra pendente":c.limit&&c.percent>=1?"Limite atingido":c.percent>=.8?"Atenção":"Normal"}</span></div><div className="cpf-stats"><div><strong>{c.used}</strong><span>CPFs utilizados</span></div><div><strong>{c.rule_pending?"—":c.limit}</strong><span>Limite</span></div><div><strong>{c.rule_pending?"—":c.remaining}</strong><span>Vagas restantes</span></div><div><strong>{c.program==="LATAM Pass"?moneyDate(c.next_release):c.program==="Smiles"?"31/12 (ano atual)":"contínuo"}</strong><span>Próxima liberação / ciclo</span></div></div>{c.history_incomplete?<p className="cpf-note">Estimativa baseada nos registros cadastrados · histórico incompleto</p>:<p className="cpf-note">Estimativa baseada nos registros cadastrados{c.program==="LATAM Pass"?" · liberação estimada pela última emissão + 12 meses":""}</p>}{c.program==="Azul Fidelidade"&&c.rule_pending?<p className="cpf-note warn">Limite sugerido pendente de confirmação pelo administrador.</p>:null}<details><summary>CPFs contabilizados ({c.cpf_rows.length})</summary><div className="table-wrap"><table><thead><tr><th>CPF</th><th>1ª emissão</th><th>Última emissão</th><th>Emissões</th><th>Liberação estimada</th></tr></thead><tbody>{c.cpf_rows.map((row,i)=><tr key={`${row.cpf}-${i}`}><td>{row.cpf}</td><td>{moneyDate(row.first)}</td><td>{moneyDate(row.last)}</td><td>{row.emissions}</td><td>{moneyDate(row.release)}</td></tr>)}</tbody></table></div></details>{data?.canManage?<div className="cpf-actions"><button className="dark-mini" onClick={()=>{const a=accounts.find(x=>x.id===c.account_id);if(a)setAccount({id:a.id,alias:a.alias,holderName:a.holder_name,holderCpf:"",program:a.program,memberNumber:a.member_number||"",azulCategory:a.azul_category||"Básico",historyIncomplete:a.history_incomplete});window.scrollTo({top:0,behavior:"smooth"});}}>Editar conta</button><button className="dark-mini" onClick={()=>void send({action:"archive",id:c.account_id,archived:!accounts.find(a=>a.id===c.account_id)?.archived})}>{accounts.find(a=>a.id===c.account_id)?.archived?"Reativar conta":"Arquivar conta"}</button></div>:null}</article>)}</div>}
      <p className="cpf-privacy">CPFs ficam mascarados nas listagens. O titular da conta não consome vaga de terceiros.</p>
    </>:null}
    {tab==="emissoes"?<>
      <form className="cpf-form" onSubmit={async e=>{e.preventDefault();const r=await send({action:"emission",...issue});if(r){setNotice((r.analysis||[]).map((x:{name:string;status:string})=>`${x.name||"Passageiro"}: ${x.status}`).join(" · "));setIssue({...issue,locator:"",airline:"",status:"emitido",notes:"",justification:"",passengers:[{name:"",cpf:""}]});}}}>
        <h2>Registrar emissão ou histórico</h2><div className="cpf-fields"><label>Conta que forneceu as milhas<select className="input" required value={issue.accountId} onChange={e=>setIssue({...issue,accountId:e.target.value})}><option value="">Selecione a conta</option>{accounts.filter(a=>!a.archived).map(a=><option key={a.id} value={a.id}>{a.program} · {a.alias} · CPF {a.holder_cpf}</option>)}</select></label><label>Data da emissão<input className="input" type="date" required value={issue.issuedOn} onChange={e=>setIssue({...issue,issuedOn:e.target.value})}/></label><label>Localizador<input className="input" value={issue.locator} onChange={e=>setIssue({...issue,locator:e.target.value})}/></label><label>Companhia operadora<input className="input" value={issue.airline} onChange={e=>setIssue({...issue,airline:e.target.value})}/></label><label>Data do voo (opcional)<input className="input" type="date" value={issue.flightOn} onChange={e=>setIssue({...issue,flightOn:e.target.value})}/></label><label>Status<select className="input" value={issue.status} onChange={e=>setIssue({...issue,status:e.target.value})}><option value="emitido">Emitido</option><option value="cancelado">Cancelado (mantém a vaga)</option><option value="correcao">Correção de cadastro</option></select></label>{issue.passengers.map((p,i)=><div className="cpf-passenger" key={i}><label>Passageiro {i+1}<input className="input" required value={p.name} onChange={e=>updatePassenger(i,"name",e.target.value)}/></label><label>CPF<input className="input" required inputMode="numeric" value={p.cpf} onChange={e=>updatePassenger(i,"cpf",e.target.value)}/></label>{issue.passengers.length>1?<button type="button" className="dark-mini" onClick={()=>setIssue({...issue,passengers:issue.passengers.filter((_,n)=>i!==n)})}>Remover</button>:null}</div>)}<button type="button" className="dark-mini" onClick={()=>setIssue({...issue,passengers:[...issue.passengers,{name:"",cpf:""}]})}>+ Passageiro</button><label className="cpf-wide">Observações<textarea className="input" value={issue.notes} onChange={e=>setIssue({...issue,notes:e.target.value})}/></label>{issue.status!=="emitido"?<label className="cpf-wide">Justificativa obrigatória<textarea className="input" required value={issue.justification} onChange={e=>setIssue({...issue,justification:e.target.value})}/></label>:null}<button className="primary-button" disabled={busy}>Registrar emissão</button></div><small>Cancelamento não libera CPF automaticamente; correções são excluídas da contagem e ficam auditadas.</small>
      </form>
      <section className="cpf-form"><h2>Histórico de emissões</h2><div className="cpf-filters"><select className="input" value={filters.program} onChange={e=>setFilters({...filters,program:e.target.value})}><option value="">Todos os programas</option><option>LATAM Pass</option><option>Smiles</option><option>Azul Fidelidade</option></select><select className="input" value={filters.account} onChange={e=>setFilters({...filters,account:e.target.value})}><option value="">Todas as contas</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.alias}</option>)}</select><input className="input" placeholder="Passageiro / CPF mascarado" value={filters.search} onChange={e=>setFilters({...filters,search:e.target.value})}/><input className="input" type="date" value={filters.from} onChange={e=>setFilters({...filters,from:e.target.value})}/><input className="input" type="date" value={filters.to} onChange={e=>setFilters({...filters,to:e.target.value})}/><select className="input" value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})}><option value="">Todos os status</option><option value="emitido">Emitido</option><option value="cancelado">Cancelado</option><option value="correcao">Correção</option></select></div><div className="table-wrap"><table><thead><tr><th>Emissão</th><th>Conta / programa</th><th>Passageiros e CPF</th><th>Localizador</th><th>Operadora</th><th>Voo</th><th>Status</th><th>Liberação</th></tr></thead><tbody>{visibleEmissions.map(e=><tr key={e.id}><td>{moneyDate(e.issued_on)}</td><td>{e.alias}<small>{e.program}</small></td><td>{data?.passengers.filter(p=>p.emission_id===e.id).map(p=><div key={p.id}>{p.name} · {p.cpf} {data?.canManage?<button className="cpf-text-button" onClick={()=>void reveal("passenger",p.id)}>ver CPF</button>:null}</div>)}</td><td>{e.locator||"—"}</td><td>{e.operating_airline||"—"}</td><td>{moneyDate(e.flight_on)}</td><td>{e.status}</td><td>{data?.canManage?data.passengers.filter(p=>p.emission_id===e.id&&!p.released_at).map(p=><button className="cpf-text-button" key={p.id} onClick={()=>{const date=window.prompt("Data de liberação confirmada pelo programa (AAAA-MM-DD)",today());const reason=date&&window.prompt("Protocolo/motivo da confirmação");if(date&&reason)void send({action:"release",passengerId:p.id,date,reason});}}>Confirmar liberação</button>):"—"}</td></tr>)}</tbody></table></div></section>
    </>:null}
    {tab==="azul"?<>
      {data?.canManage?<form className="cpf-form" onSubmit={async e=>{e.preventDefault();const r=await send({action:"beneficiary",...beneficiary});if(r){setBeneficiary({...beneficiary,name:"",cpf:""});setNotice("Beneficiário registrado.");}}}><h2>Novo beneficiário Azul</h2><div className="cpf-fields"><label>Conta<select className="input" required value={beneficiary.accountId} onChange={e=>setBeneficiary({...beneficiary,accountId:e.target.value})}><option value="">Selecione</option>{azulAccounts.map(a=><option key={a.id} value={a.id}>{a.alias} · {a.azul_category}</option>)}</select></label><label>Nome<input className="input" required value={beneficiary.name} onChange={e=>setBeneficiary({...beneficiary,name:e.target.value})}/></label><label>CPF<input className="input" required inputMode="numeric" value={beneficiary.cpf} onChange={e=>setBeneficiary({...beneficiary,cpf:e.target.value})}/></label><label>Data efetiva<input className="input" type="date" required value={beneficiary.effectiveOn} onChange={e=>setBeneficiary({...beneficiary,effectiveOn:e.target.value})}/></label><label>Inclusão<select className="input" value={beneficiary.inclusionType} onChange={e=>setBeneficiary({...beneficiary,inclusionType:e.target.value})}><option value="inicial">Inicial</option><option value="substituicao">Substituição</option></select></label><label className="cpf-check"><input type="checkbox" checked={beneficiary.isChild} onChange={e=>setBeneficiary({...beneficiary,isChild:e.target.checked})}/> Filho(a)</label>{beneficiary.isChild?<><label className="cpf-check"><input type="checkbox" checked={beneficiary.relationshipConfirmed} onChange={e=>setBeneficiary({...beneficiary,relationshipConfirmed:e.target.checked})}/> Vínculo confirmado pelo programa</label><label className="cpf-check"><input type="checkbox" checked={beneficiary.exemptionConfirmed} onChange={e=>setBeneficiary({...beneficiary,exemptionConfirmed:e.target.checked})}/> Isenção confirmada pelo programa</label></>:null}<button className="primary-button" disabled={busy}>Cadastrar beneficiário</button></div><small>Cadastro ocupa vaga; substituições usam carência configurada. Remoção mantém histórico.</small></form>:null}
      {cards.filter(c=>c.program==="Azul Fidelidade").map(c=><section className="cpf-form" key={c.account_id}><h2>{c.alias} · {c.holder_name}</h2><p>Vagas ativas: {c.used} / {c.rule_pending?"limite pendente":c.limit} · Básico/Topázio/Safira/Diamante/Diamante Unique: sugestões de 7/8/9/10/15, pendentes de confirmação.</p><div className="table-wrap"><table><thead><tr><th>Beneficiário</th><th>CPF</th><th>Cadastro efetivo</th><th>Status</th><th>Liberação</th><th>Inclusão</th><th>Ações</th></tr></thead><tbody>{c.azul_beneficiaries.map(b=><tr key={b.id}><td>{b.name}</td><td>{b.cpf} {data?.canManage?<button className="cpf-text-button" onClick={()=>void reveal("beneficiary",b.id)}>ver CPF</button>:null}</td><td>{moneyDate(b.effective_on)}</td><td>{b.status}{b.release_on&&b.release_on>today()?" · em carência":""}</td><td>{moneyDate(b.release_on)}</td><td>{b.inclusion_type}</td><td>{data?.canManage?<button className="dark-mini" onClick={()=>{const releaseOn=window.prompt("Data de liberação informada pelo programa (AAAA-MM-DD); deixe vazio se não aplicável","");const reason=window.prompt("Justificativa / confirmação do programa");if(reason)void send({action:"beneficiary-update",id:b.id,status:b.status==="removido"?"ativo":"removido",removedOn:b.status==="removido"?null:today(),releaseOn,releaseReason:reason});}}>{b.status==="removido"?"Reativar":"Registrar remoção"}</button>:"—"}</td></tr>)}</tbody></table></div></section>)}
    </>:null}
    {tab==="regras"&&data?.canManage?<form className="cpf-form" onSubmit={async e=>{e.preventDefault();const r=await send({action:"rule",...rule,limit:Number(rule.limit),waitingDays:Number(rule.waitingDays)});if(r)setNotice("Regra versionada; confira a vigência e a fonte.");}}><h2>Regras e limites · histórico mantido</h2><div className="cpf-fields"><label>Programa<select className="input" value={rule.program} onChange={e=>{const program=e.target.value;setRule({...rule,program,accountId:"",limit:program==="LATAM Pass"?"24":program==="Smiles"?"25":"7",confirmed:false});}}><option>LATAM Pass</option><option>Smiles</option><option>Azul Fidelidade</option></select></label>{rule.program==="Azul Fidelidade"?<label>Conta Azul<select className="input" required value={rule.accountId} onChange={e=>{const a=accounts.find(x=>x.id===e.target.value);const suggested=({Básico:7,Topázio:8,Safira:9,Diamante:10,"Diamante Unique":15} as Record<string,number>)[a?.azul_category||""]||7;setRule({...rule,accountId:e.target.value,limit:String(suggested)});}}><option value="">Selecione a conta</option>{azulAccounts.map(a=><option key={a.id} value={a.id}>{a.alias} · {a.azul_category}</option>)}</select></label>:null}<label>Limite sugerido / confirmado<input className="input" type="number" min="1" max="100" required value={rule.limit} onChange={e=>setRule({...rule,limit:e.target.value})}/></label><label>Carência (dias)<input className="input" type="number" min="0" max="365" value={rule.waitingDays} onChange={e=>setRule({...rule,waitingDays:e.target.value})}/></label><label>Fonte / justificativa<input className="input" required value={rule.source} onChange={e=>setRule({...rule,source:e.target.value})}/></label><label>Vigência desde<input className="input" type="date" required value={rule.validFrom} onChange={e=>setRule({...rule,validFrom:e.target.value})}/></label><label>Conferida em<input className="input" type="date" required value={rule.checkedOn} onChange={e=>setRule({...rule,checkedOn:e.target.value})}/></label>{rule.program==="Azul Fidelidade"?<label className="cpf-check"><input type="checkbox" checked={rule.confirmed} onChange={e=>setRule({...rule,confirmed:e.target.checked})}/> Confirmo o limite efetivo informado pelo programa</label>:null}<button className="primary-button" disabled={busy}>Salvar nova versão</button></div><div className="table-wrap"><table><thead><tr><th>Programa</th><th>Conta</th><th>Limite</th><th>Carência</th><th>Fonte</th><th>Vigência</th><th>Conferida</th><th>Status</th></tr></thead><tbody>{data.rules.map((r,i)=><tr key={`${r.program}-${r.account_id}-${i}`}><td>{r.program}</td><td>{accounts.find(a=>a.id===r.account_id)?.alias||"Regra geral"}</td><td>{r.limit_count}</td><td>{r.waiting_days} dias</td><td>{r.source}</td><td>{moneyDate(r.valid_from)}</td><td>{moneyDate(r.checked_on)}</td><td>{r.active?"Atual":"Histórico"}</td></tr>)}</tbody></table></div></form>:null}
  </div>;
}
